
// 公共
export const COMMON_SHOW_ALERT = 'COMMON_SHOW_ALERT'
export const COMMON_CLOSE_ALERT = 'COMMON_CLOSE_ALERT'
export const COMMON_SET_SPINNER = 'COMMON_SET_SPINNER'
export const COMMON_SET_SENSITIVE_WORDS = 'COMMON_SET_SENSITIVE_WORDS'
export const COMMON_SET_COMMENTS = 'COMMON_SET_COMMENTS'
// 发表评论
export const COMMON_ADD_COMMENT = 'COMMON_ADD_COMMENTS'
// 回复
export const COMMON_ADD_REPLY = 'COMMON_ADD_REPLY'
export const COMMON_SET_LIKE_STATUS = 'COMMON_SET_LIKE_STATUS'
export const COMMON_GET_COLLECTIONS = 'COMMON_GET_COLLECTIONS'
export const COMMON_ADD_COLLECTION = 'COMMON_ADD_COLLECTION'

/**
 * 用户
 * @type {string}
 */
export const USER_SET_USER = 'USER_SET_USER'
export const USER_GET_USER_FROM_LOCAL = 'USER_GET_USER_FROM_LOCAL'
export const USER_CLEAR = 'USER_CLEAR'


/**
 * 新闻
 * @type {string}
 */
export const NEWS_SET_NEWS_NAVS = 'NEWS_SET_NEWS_NAVS'
export const NEWS_SET_NEWS_LIST = 'NEWS_SET_NEWS_LIST'
export const NEWS_CLEAR_NEWS_LIST = 'NEWS_CLEAR_NEWS_LIST'

export const NEWS_GET_NEWS_DETAIL = 'NEWS_GET_NEWS_DETAIL'
export const NEWS_LIKE_NEWS = 'NEWS_LIKE_NEWS'
// 举报
export const NEWS_REPORT_NEWS = 'NEWS_REPORT_NEWS'
export const NEWS_COMMENT_NEWS = 'NEWS_COMMENT_NEWS'


/**
 * 视频
 * @type {string}
 */
export const VIDEO_SET_INDEX_VIDEOS = 'VIDEO_SET_INDEX_VIDEOS'
export const VIDEO_SET_RECOMMEND_VIDEOS = 'VIDEO_SET_RECOMMEND_VIDEOS'
export const VIDEO_SET_VIDEOS = 'VIDEO_SET_VIDEOS'
export const VIDEO_SET_VIDEO = 'VIDEO_SET_VIDEO'


/**
 * 图片
 * @type {string}
 */
export const PICTURE_SET_PICTURES = 'PICTURE_SET_PICTURES'



